name: Build LaTeX and Release PDF

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install LaTeX dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-full \
          fonts-noto-cjk \
          fonts-noto

    - name: Compile LaTeX document
      run: |
        # 多次编译确保正确
        xelatex -interaction=nonstopmode -halt-on-error main.tex || exit 1
        xelatex -interaction=nonstopmode -halt-on-error main.tex || exit 1

    - name: Verify PDF was created
      run: |
        if [ ! -f "main.pdf" ]; then
          echo "PDF was not created!"
          exit 1
        fi
        echo "PDF size: $(du -h main.pdf)"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: main.pdf
        body: |
          自动生成的 PDF 文档
          版本: ${{ github.ref_name }}
          编译时间: ${{ utcnow() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}